version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo

volumes:
  mongo-data:
